### ISSUE TITLE
Invalid Push formate

### ISSUE THREAD

**Issue by Hamzify** [monal-im/fpush#20]
Greetings!
we are sending stanza you have mentioned in readme file but the issue is when we try to send notification it shows this error  fpush.chat.woooo.world rejected notification for +81456467676@chat.woooo.world (AC4089A5DB07A714164490065F9ACB565EE4A19D1DA95C1D839A2F84B8A1294E) temporarily: Invalid push format, update your prosody community modules (debian stable has a bug, use backports instead) (bad-request)
can you guide me what is the issue

```
<iq type='set' id='x43'>
  <enable xmlns='urn:xmpp:push:0' jid='###pushServerComponentJid###' node='###DevicePushToken###'>
    <x xmlns='jabber:x:data' type='submit'>
      <field var='FORM_TYPE'><value>http://jabber.org/protocol/pubsub#publish-options</value></field>
      <field var='pushModule'><value>##pushModuleName###</value></field>
    </x>
  </enable>
</iq>
```

this is the stanza we are sending.
we are using siskin app for ios and conversation for android.

**Comment by FriedrichAltheide** [comment]
You presumably have installed an old prosody version on your XMPP server.
As stated by the error message you should update to a newer prosody version and/or prosody community module version on your xmpp server. After that the error should be gone.

**Comment by Hamzify** [comment]
> You presumably have installed an old prosody version on your XMPP server. As stated by the error message you should update to a newer prosody version and/or prosody community module version on your xmpp server. After that the error should be gone.

I'm using ejabberd and want to configure fpush with ejabberd xmpp server, how can I configure it with my ejabberd ?

**Comment by FriedrichAltheide** [comment]
You do not need fpush if you are using stock siskin and conversations

**Comment by Hamzify** [comment]
Then how can we use push notification service because we are not using stock siskin we are building it in our own app and want to configure it for push because push is not working. kindly let me know

**Comment by tmolitor-stud-tu** [comment]
Don't use Siskin, their push works completely differently to that of Conversations or Monal.

Why use Siskin in the first place?

**Comment by Hamzify** [comment]
thanks
