### ISSUE TITLE
Apple notification object issue

### ISSUE THREAD

**Issue by Hamzify** [monal-im/fpush#24]
#[async_trait]
impl PushTrait for FpushApns {
    #[inline(always)]
    async fn send(&self, token: String) -> PushResult<()> {
        let notification_builder = DefaultNotificationBuilder::new()
            .set_title("New Message")
            .set_body("New Message?")
            .set_mutable_content()
            .set_sound("default");
        let mut payload = notification_builder.build(
            &token,
            NotificationOptions {
                apns_priority: Some(Priority::High),
                apns_topic: Some(&self.topic),
                apns_expiration: Some(
                    SystemTime::now().elapsed().unwrap().as_secs() + 4 * 7 * 24 * 3600,
                ),
                apns_push_type: Some(PushType::Alert),
                ..Default::default()
            },
        );
        match &self.additional_data {
            None => {}
            Some(additional_data) => {
                for (key, value) in additional_data {
                    payload.add_custom_data(key, value).unwrap();
                }
            }
        }
        log::debug!(
            "Payload send to apple: {}",
            payload.clone().to_json_string().unwrap()
        );
        match self.apns.send(payload).await {
            Ok(response) => {
                debug!(
                    "Got response {} from apple for token {}",
                    response.code, token
                );
                response_code_to_push_error(response.code)
            }
            Err(e) => {
                error!("Could not send apns message to apple: {}", e);
                if let a2::Error::ResponseError(response) = e {
                    return response_code_to_push_error(response.code);
                }
                Err(PushError::PushEndpointTmp)
            }
        }
    }
}
Hi I want to understand one thing. in this code whenever I send push notifications through Monal I get the string in notification "new message" that you already mentioned in notifcation object and I want to know  how I will pass user message in notification object to get message and user name through push notifcation?

**Comment by FriedrichAltheide** [comment]
fpush does not implement passing messages to apns.

**Comment by Hamzify** [comment]
> fpush does not implement passing messages to apns.

can you tell me the stanza we are passing to ejabberd xmpp server on sending messages is passed by fpush to apns?

**Comment by tmolitor-stud-tu** [comment]
fpush does not forward anything but the push token received by ejabberd to apns. And it does not receive message contents from ejabberd either. See the documentation anx xep-0357 for a full example.

**Comment by Hamzify** [comment]
> fpush does not forward anything but the push token received by ejabberd to apns. And it does not receive message contents from ejabberd either. See the documentation anx xep-0357 for a full example.

then what is the use case of this proxy?

**Comment by tmolitor-stud-tu** [comment]
The usecase is that an xmpp app developer usually does not control the xmpp server the user is using, but that server wants to generate push notifications. It can't do so directly, because on Google and Apple platforms, only the app developer is allowed to generate pushes. So the xmpp server has to send the push request to a server of the app developer which will proxy it to Apple's APNS or Google's FCM. That's what fpush does.

**Comment by tmolitor-stud-tu** [comment]
Monal only uses a push to wake up in the background, connect to the actual xmpp server and retrieve the messages waiting to be delivered. Then it displays notifications for those messages (if that chat isn't muted etc.).

**Comment by tmolitor-stud-tu** [comment]
--> See the slides of "Privacy friendly push" over here: https://monal-im.org/publications/ starting with page 29

**Comment by Hamzify** [comment]
> The usecase is that an xmpp app developer usually does not control the xmpp server the user is using, but that server wants to generate push notifications. It can't do so directly, because on Google and Apple platforms, only the app developer is allowed to generate pushes. So the xmpp server has to send the push request to a server of the app developer which will proxy it to Apple's APNS or Google's FCM. That's what fpush does.

Last thing is there any payload sent in notification?

**Comment by tmolitor-stud-tu** [comment]
I already answered that
