### ISSUE TITLE
fpush error in prosody

### ISSUE THREAD

**Issue by devs-bg** [monal-im/fpush#5]
Hello All, I try to use fpush in prosody setup the component and used ios Monal to use it with my push service

I got this error

May 08 13:16:54 escapethenet.com systemd[1]: fpush.service: Consumed 2.032s CPU time.
May 08 13:16:54 escapethenet.com systemd[1]: Started Fpush.
May 08 13:16:54 escapethenet.com fpush[58276]: [2023-05-08T10:16:54Z INFO  fpush] Loading config file settings.json
May 08 13:16:54 escapethenet.com fpush[58276]: [2023-05-08T10:16:54Z DEBUG fpush] Config loaded
May 08 13:16:54 escapethenet.com fpush[58276]: [2023-05-08T10:16:54Z INFO  fpush_push] Loading EscapeProdiOS as default push module
May 08 13:16:54 escapethenet.com fpush[58276]: [2023-05-08T10:16:54Z INFO  fpush] Opening connection to escapethenet.com
May 08 13:16:54 escapethenet.com fpush[58276]: [2023-05-08T10:16:54Z DEBUG tokio_xmpp::xmpp_codec] >> "<stream:stream version=\"1.0\" xmlns:stream=\"http://etherx.jabber.org/streams\" to=\"push.escapethenet.com\" xmlns=\"jabber:component:accept\">\n"
May 08 13:16:54 escapethenet.com fpush[58276]: [2023-05-08T10:16:54Z DEBUG tokio_xmpp::xmpp_codec] >> b"<handshake xmlns='jabber:component:accept' id=\"14960931040889814192\">8faabd38ea789bacd03857b20817bcbf312b0d2e</handshake>"
May 08 13:17:31 escapethenet.com fpush[58276]: [2023-05-08T10:17:31Z DEBUG tokio_xmpp::xmpp_codec] >> b"<iq xmlns='jabber:component:accept' from=\"push.escapethenet.com\" id=\"40282266-C56E-454B-9D32-B888320705B6\" to=\"daniel@escapethenet.com/Monal-iOS.dc6c4673\" type=\"error\"><error type=\"cancel\"><bad-request xmlns='urn:ietf:>
May 08 13:17:31 escapethenet.com fpush[58276]: [2023-05-08T10:17:31Z DEBUG tokio_xmpp::xmpp_codec] >> b"<iq xmlns='jabber:component:accept' from=\"push.escapethenet.com\" id=\"3C1D2F05-BF65-4CBF-861D-4F5F2FC2A46A\" to=\"daniel@escapethenet.com/Monal-iOS.dc6c4673\" type=\"error\"><error type=\"cancel\"><bad-request xmlns='urn:ietf:>
May 08 13:17:44 escapethenet.com fpush[58276]: [2023-05-08T10:17:44Z DEBUG tokio_xmpp::xmpp_codec] >> b"<iq xmlns='jabber:component:accept' from=\"push.escapethenet.com\" id=\"8BA49A86-6D20-4CAF-B9B5-60D615558368\" to=\"daniel@escapethenet.com/Monal-iOS.843ea780\" type=\"error\"><error type=\"cancel\"><bad-request xmlns='urn:ietf:>
May 08 13:21:51 escapethenet.com fpush[58276]: [2023-05-08T10:21:51Z DEBUG fpush::xmpp::message_loop] Selected push_module monalProdiOS for JID escapethenet.com with token 20a5acff12d78c960b9f1fc25328428f3253b7fdf5f43c805613e3ab239b3299
May 08 13:21:51 escapethenet.com fpush[58276]: [2023-05-08T10:21:51Z DEBUG fpush_push] Unkown push_module requested: monalProdiOS
May 08 13:21:51 escapethenet.com fpush[58276]: [2023-05-08T10:21:51Z WARN  fpush::xmpp::message_loop] monalProdiOS: Unkown push module requested for token 20a5acff12d78c960b9f1fc25328428f3253b7fdf5f43c805613e3ab239b3299 from escapethenet.com
May 08 13:21:51 escapethenet.com fpush[58276]: [2023-05-08T10:21:51Z DEBUG tokio_xmpp::xmpp_codec] >> b"<iq xmlns='jabber:component:accept' from=\"push.escapethenet.com\" id=\"9b4afef6360c5e9236f88072b4f8f7d9389ed936a03c95d72f8ea8ab200df126\" to=\"escapethenet.com\" type=\"error\"><error type=\"cancel\"><bad-request xmlns='urn:iet>
May 08 13:21:53 escapethenet.com fpush[58276]: [2023-05-08T10:21:53Z DEBUG fpush::xmpp::message_loop] Selected push_module monalProdiOS for JID escapethenet.com with token 20a5acff12d78c960b9f1fc25328428f3253b7fdf5f43c805613e3ab239b3299
May 08 13:21:53 escapethenet.com fpush[58276]: [2023-05-08T10:21:53Z DEBUG fpush_push] Unkown push_module requested: monalProdiOS
May 08 13:21:53 escapethenet.com fpush[58276]: [2023-05-08T10:21:53Z WARN  fpush::xmpp::message_loop] monalProdiOS: Unkown push module requested for token 20a5acff12d78c960b9f1fc25328428f3253b7fdf5f43c805613e3ab239b3299 from escapethenet.com
May 08 13:21:53 escapethenet.com fpush[58276]: [2023-05-08T10:21:53Z DEBUG fpush::xmpp::message_loop] Selected push_module monalProdiOS for JID escapethenet.com with token 20a5acff12d78c960b9f1fc25328428f3253b7fdf5f43c805613e3ab239b3299
May 08 13:21:53 escapethenet.com fpush[58276]: [2023-05-08T10:21:53Z DEBUG fpush_push] Unkown push_module requested: monalProdiOS
May 08 13:21:53 escapethenet.com fpush[58276]: [2023-05-08T10:21:53Z WARN  fpush::xmpp::message_loop] monalProdiOS: Unkown push module requested for token 20a5acff12d78c960b9f1fc25328428f3253b7fdf5f43c805613e3ab239b3299 from escapethenet.com
May 08 13:21:53 escapethenet.com fpush[58276]: [2023-05-08T10:21:53Z DEBUG tokio_xmpp::xmpp_codec] >> b"<iq xmlns='jabber:component:accept' from=\"push.escapethenet.com\" id=\"ad75e60ed2df0db46dd3834997db55577133f39e89a93378f4990a58e3dec387\" to=\"escapethenet.com\" type=\"error\"><error type=\"cancel\"><bad-request xmlns='urn:iet>
May 08 13:21:53 escapethenet.com fpush[58276]: [2023-05-08T10:21:53Z DEBUG tokio_xmpp::xmpp_codec] >> b"<iq xmlns='jabber:component:accept' from=\"push.escapethenet.com\" id=\"17277031e3a5a17d76baf96356bb8f23f4fc95bd194f23a509d5c9e431fd8666\" to=\"escapethenet.com\" type=\"error\"><error type=\"cancel\"><bad-request xmlns='urn:iet>

**Comment by FriedrichAltheide** [comment]
just use monal...

**Comment by FriedrichAltheide** [comment]
Now the longer version:

Have you read xep-0357? Have you had a look at the slides of the presentation that Thilo gave in Berlin regarding push? Or the the wiki article in the xmpp wiki? Have you read the README of fpush? And of course, have you read the error message? The error message is quite clear. So please read the articles and familiarize yourself with the push concept of fpush before continuing developing a fork of Monal.

_For anyone else reading this issue:_

- **If you use Monal (installed from the Appstore, brew or manually)** you do not need to run fpush on your server. Instead check that your XMPP server has xep-0357 enabled (Can be checked within Monal). And check that s2s connections are indeed allowed to our Monal push servers. Then our push servers will be used, just as intended.
- **If you indeed forked Monal** or you want to use fpush for other apps like conversations (requires a patch) you just have to read the articles mentioned above and understand them and then configure fpush and your forked Monal accordingly.
As of today I am aware of at least four other apps (android and iOS) that are successfully using fpush just by reading the README and understanding the push concept of XMPP as well as our privacy friendly push design.

**Comment by devs-bg** [comment]
Dear [FriedrichAltheide],
Thank you for your support. 
Of course first read the Readme and the documents the problem was missing in the Push module name so I just renamed in Xcode and all working fine because it was searching for monalProdiOS

I am closing the ticket but please be more generous if its possible.
